### ISSUE TITLE
face-up promicro on Reviung41-lp2 version

### ISSUE THREAD

**Issue by kh411d** [cyril279/keyboards#1]
I've just realized it after I complete the build for the kailh choc v2 version that the pro micro is face-up, I don't know whether this is reversible or not, I'm planning to replace the controller with nice!nano in the future and most likely I prefer to be face-down

**Comment by cyril279** [comment]
For nice!nano use, face-up is usually preferred for two main reasons:  
1) When fitting a battery under the controller, the face-up orientation naturally lends itself to better fitment  
2) The led's of the nice!nano are only lit during charging or flashing (unlike the elite-c, or pro-micro, etc), so there is less interest in hiding them. They are actually beneficial to see, and less of a nuisance.    

I have no plans to alter the design to make the controller face-up (or re-route the board to make it optional).  
This project can be forked, and modified to your particular liking, and I encourage you to do so.  
There are several open-source projects that exhibit dual-mounting options for the controller-footprint.
